<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchPost($searchWord = null)
    {
        $queryBuilder = $this->createQueryBuilder('bp');
        if ($searchWord) {
            $queryBuilder->where('bp.title LIKE :title')
                ->setParameter('title', '%' . $searchWord . '%');
        }
        return $queryBuilder->getQuery();
    }
}
