# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    session.handler.dbal:
        class: Symfony\Bridge\Doctrine\HttpFoundation\DbalSessionHandler
        public: false
        arguments:
            - "@database_connection"

    gelf.transport:
        class: Gelf\Transport\UdpTransport
        arguments: ["%graylog_hostname%", "%graylog_port%"]

    gelf.publisher:
        class: Gelf\Publisher
        arguments: ["@gelf.transport"]

    monolog.processor.web_processor:
        class: Monolog\Processor\WebProcessor
        tags:
          - { name: monolog.processor, method: __invoke }

    app.service.file_loader:
        class: AppBundle\Service\FileUploader
        arguments: ['%image_directory%']

    app.listener.post_upload:
        class: AppBundle\EventListener\PostUploadListener
        arguments: ['@app.service.file_loader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    admin.post:
            class: AppBundle\Admin\PostAdmin
            arguments: [~, AppBundle\Entity\Post, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Post }
            public: true